//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Единицы.
    /// </summary>
    // *** Start programmer edit section *** (Единицы CustomAttributes)

    // *** End programmer edit section *** (Единицы CustomAttributes)
    public enum Единицы
    {
        
        // *** Start programmer edit section *** (Единицы.1 CustomAttributes)

        // *** End programmer edit section *** (Единицы.1 CustomAttributes)
        [Caption("Шт")]
        1,
        
        // *** Start programmer edit section *** (Единицы.2 CustomAttributes)

        // *** End programmer edit section *** (Единицы.2 CustomAttributes)
        [Caption("Кг")]
        2,
        
        // *** Start programmer edit section *** (Единицы.3 CustomAttributes)

        // *** End programmer edit section *** (Единицы.3 CustomAttributes)
        [Caption("Г")]
        3,
    }
}
