//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поставщики.
    /// </summary>
    // *** Start programmer edit section *** (Поставщики CustomAttributes)

    // *** End programmer edit section *** (Поставщики CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоставщикиE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [View("ПоставщикиL", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "НомерТелефона as \'Номер телефона\'"})]
    public class Поставщики : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private int fНомерТелефона;
        
        // *** Start programmer edit section *** (Поставщики CustomMembers)

        // *** End programmer edit section *** (Поставщики CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Поставщики.ID CustomAttributes)

        // *** End programmer edit section *** (Поставщики.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Поставщики.ID Get start)

                // *** End programmer edit section *** (Поставщики.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Поставщики.ID Get end)

                // *** End programmer edit section *** (Поставщики.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщики.ID Set start)

                // *** End programmer edit section *** (Поставщики.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Поставщики.ID Set end)

                // *** End programmer edit section *** (Поставщики.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Поставщики.Наименование CustomAttributes)

        // *** End programmer edit section *** (Поставщики.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Поставщики.Наименование Get start)

                // *** End programmer edit section *** (Поставщики.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Поставщики.Наименование Get end)

                // *** End programmer edit section *** (Поставщики.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщики.Наименование Set start)

                // *** End programmer edit section *** (Поставщики.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Поставщики.Наименование Set end)

                // *** End programmer edit section *** (Поставщики.Наименование Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Поставщики.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Поставщики.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Поставщики.НомерТелефона Get start)

                // *** End programmer edit section *** (Поставщики.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Поставщики.НомерТелефона Get end)

                // *** End programmer edit section *** (Поставщики.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщики.НомерТелефона Set start)

                // *** End programmer edit section *** (Поставщики.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Поставщики.НомерТелефона Set end)

                // *** End programmer edit section *** (Поставщики.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоставщикиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикиE", typeof(IIS.Sonya3.Поставщики));
                }
            }
            
            /// <summary>
            /// "ПоставщикиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикиL", typeof(IIS.Sonya3.Поставщики));
                }
            }
        }
    }
}
