//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав материалы.
    /// </summary>
    // *** Start programmer edit section *** (СоставМатериалы CustomAttributes)

    // *** End programmer edit section *** (СоставМатериалы CustomAttributes)
    [AutoAltered()]
    [Caption("Состав материалы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставМатериалыE", new string[] {
            "Количество as \'Количество\'",
            "Материалы as \'Материалы\'",
            "Материалы.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Материалы.Наименование"})]
    [MasterViewDefineAttribute("СоставМатериалыE", "Материалы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СоставМатериалы : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Sonya3.Материалы fМатериалы;
        
        private IIS.Sonya3.РасходДенег fРасходДенег;
        
        // *** Start programmer edit section *** (СоставМатериалы CustomMembers)

        // *** End programmer edit section *** (СоставМатериалы CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставМатериалы.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставМатериалы.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставМатериалы.Количество Get start)

                // *** End programmer edit section *** (СоставМатериалы.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СоставМатериалы.Количество Get end)

                // *** End programmer edit section *** (СоставМатериалы.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставМатериалы.Количество Set start)

                // *** End programmer edit section *** (СоставМатериалы.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставМатериалы.Количество Set end)

                // *** End programmer edit section *** (СоставМатериалы.Количество Set end)
            }
        }
        
        /// <summary>
        /// Состав материалы.
        /// </summary>
        // *** Start programmer edit section *** (СоставМатериалы.Материалы CustomAttributes)

        // *** End programmer edit section *** (СоставМатериалы.Материалы CustomAttributes)
        [PropertyStorage(new string[] {
                "Материалы"})]
        [NotNull()]
        public virtual IIS.Sonya3.Материалы Материалы
        {
            get
            {
                // *** Start programmer edit section *** (СоставМатериалы.Материалы Get start)

                // *** End programmer edit section *** (СоставМатериалы.Материалы Get start)
                IIS.Sonya3.Материалы result = this.fМатериалы;
                // *** Start programmer edit section *** (СоставМатериалы.Материалы Get end)

                // *** End programmer edit section *** (СоставМатериалы.Материалы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставМатериалы.Материалы Set start)

                // *** End programmer edit section *** (СоставМатериалы.Материалы Set start)
                this.fМатериалы = value;
                // *** Start programmer edit section *** (СоставМатериалы.Материалы Set end)

                // *** End programmer edit section *** (СоставМатериалы.Материалы Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Sonya3.РасходДенег.
        /// </summary>
        // *** Start programmer edit section *** (СоставМатериалы.РасходДенег CustomAttributes)

        // *** End programmer edit section *** (СоставМатериалы.РасходДенег CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасходДенег"})]
        public virtual IIS.Sonya3.РасходДенег РасходДенег
        {
            get
            {
                // *** Start programmer edit section *** (СоставМатериалы.РасходДенег Get start)

                // *** End programmer edit section *** (СоставМатериалы.РасходДенег Get start)
                IIS.Sonya3.РасходДенег result = this.fРасходДенег;
                // *** Start programmer edit section *** (СоставМатериалы.РасходДенег Get end)

                // *** End programmer edit section *** (СоставМатериалы.РасходДенег Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставМатериалы.РасходДенег Set start)

                // *** End programmer edit section *** (СоставМатериалы.РасходДенег Set start)
                this.fРасходДенег = value;
                // *** Start programmer edit section *** (СоставМатериалы.РасходДенег Set end)

                // *** End programmer edit section *** (СоставМатериалы.РасходДенег Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставМатериалыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставМатериалыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставМатериалыE", typeof(IIS.Sonya3.СоставМатериалы));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставМатериалы.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставМатериалы CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставМатериалы CustomAttributes)
    public class DetailArrayOfСоставМатериалы : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Sonya3.DetailArrayOfСоставМатериалы members)

        // *** End programmer edit section *** (IIS.Sonya3.DetailArrayOfСоставМатериалы members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставМатериалы by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставМатериалы.
        /// </summary>
        public DetailArrayOfСоставМатериалы(IIS.Sonya3.РасходДенег fРасходДенег) : 
                base(typeof(СоставМатериалы), ((ICSSoft.STORMNET.DataObject)(fРасходДенег)))
        {
        }
        
        public IIS.Sonya3.СоставМатериалы this[int index]
        {
            get
            {
                return ((IIS.Sonya3.СоставМатериалы)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Sonya3.СоставМатериалы dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
